---
title: "583 top CpG"
author: "Guannan Shen"
date: "November 1, 2018"
output: 
  pdf_document:
    latex_engine: lualatex
    number_sections: yes
    toc: yes
    toc_depth: 5
  word_document:
    toc: yes
    toc_depth: '5'
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
opts_chunk$set(engine = "R")
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
## setting working directory in asus 
## opts_knit$set(root.dir = "C:/Users/hithr/Documents/Stats/gitlab/ECCHO_Guannan/Code/")
## setting working directory in ubuntu
opts_knit$set(root.dir = "~/Documents/gitlab/ECCHO_github/Reports/")
                                                 
## cache = F, if cache = T, will not revaluate code chunk everytime
## double or more space to insert a line break
```


```{r libs}
## set up workspace
library(knitr)
library(tidyverse)
options(stringsAsFactors = F)
options(dplyr.width = Inf)
getwd()
'%nin%' <- Negate('%in%')
```

```{r readinData}
## top CpG for male and female
## male 103 and female 38
cpg_male <- read.delim("~/Documents/gitlab/ECCHO_github/DataRaw/583_top_CpG_from_DMR_adjusted_M005.txt")
dim(cpg_male)
cpg_female <- read.delim("~/Documents/gitlab/ECCHO_github/DataRaw/583_top_CpG_from_DMR_adjusted_F005.txt")
dim(cpg_female)
## the list of top cpg 
male103 <-  cpg_male$CpG
female38 <- cpg_female$CpG

### import M values for top CpGs of female and male 
m103 <- read_csv("~/Documents/gitlab/ECCHO_github/DataRaw/HS_450K_CB_Mval_normbatch_StarlingSubset_MALE_10-29-18.csv")
dim(m103)
f38  <- read_csv("~/Documents/gitlab/ECCHO_github/DataRaw/HS_450K_CB_Mval_normbatch_StarlingSubset_FEMALE_10-29-18.csv")
dim(f38)

## double check the CpG list 
sum(male103 %in% colnames(m103[,-1])) == length(male103)
sum(female38 %in% colnames(f38[,-1])) == length(female38)

## get the 583 subjects list 
pid583 <- read.csv("~/Documents/gitlab/ECCHO_github/DataRaw/pid583.csv")
pid583 <- as.vector(unlist(pid583))
## clinical data and cord blood cell types   
pfas <- read_csv("~/Documents/gitlab/ECCHO_github/DataRaw/pfas_methyl_di.csv")
celltype <- read_csv("~/Documents/gitlab/ECCHO_github/DataProcessed/healthy_start_cordblood_cellcounts_id.txt")

## inner joint, in the clinical data, 2 levels Race. 
pfas_cell <- merge(pfas, celltype, by = "pid") %>% rename(Race = race_4) %>% 
  select(pid, infant_sex, maternal_age, Race, everything()) %>% 
  mutate(Race = fct_collapse(as.factor(Race), 
                             "Non-Hispanic white" = "2",
                             "All others" = c("1", "3", "4")))
## clinical, cell types and 103 CpGs for male
pfas_malecpg <- merge(pfas_cell, m103, by = "pid") %>% 
  filter(pid %in% pid583) %>% filter(infant_sex == 2)
dim(pfas_malecpg)

## clinical, cell types and 38 CpGs for female 
pfas_femalecpg <- merge(pfas_cell, f38, by = "pid") %>% 
  filter(pid %in% pid583) %>% filter(infant_sex == 1)
dim(pfas_femalecpg)

## variables besides CpGs
## not cpg part
out_cov <- colnames(pfas_cell)
## the outcomes vector
Outcomes <- colnames(pfas_cell)[5:13]

## save dataset 
write.csv(pfas_malecpg, "~/Documents/gitlab/ECCHO_github/DataProcessed/11_05_pfas_malecpg.csv")
write.csv(pfas_femalecpg, "~/Documents/gitlab/ECCHO_github/DataProcessed/11_05_pfas_femalecpg.csv")


```

```{r FunRegSim}
####################################
###### No maternal_age   ###########
####################################
## equal length of outcomes and covariates
cpg_FunRegSim <- function(outcome, CpGdata, Xs, Outcome_name, Topn, Gender){
  ## number of CpG to test, also the number of multiple test
  n_cpg = ncol(CpGdata)
  ## outcome lm
  outcome_lm = lapply(1:n_cpg, function(i){
  lm = lm(outcome ~ CpGdata[ ,i] + Race + Bcell + CD4T +
            CD8T + Gran + Mono + NK + nRBC, data = Xs)
  coef = summary(lm)$coefficients[2, ]
  return(coef)
})
   outcome_lm = data.frame(matrix(unlist(outcome_lm), ncol = 4, byrow = TRUE,
                          dimnames = list(
                     c(colnames(CpGdata)),
                        c("Estimate", "Std.Error", "t.statistic", "p.value"))))

   # adjusted p-value
    outcome_lm =  outcome_lm %>% 
                              mutate(FDR = p.adjust(p.value, "BH", n_cpg ),
                                               names = colnames(CpGdata)) %>% 
                                               mutate(Estimate = round(Estimate ,4),
                                                      Std.Error = round(Std.Error,4),
                                                      t.statistic = round(t.statistic,4)
                                                      )%>% 
                                               select(names, everything())
   # sort by p.value
    outcome_lm = outcome_lm[order(outcome_lm$p.value), ]
 
   ## sample size 
    size = length(outcome) - sum(is.na(outcome))

   ## summary table 
   kable(head(outcome_lm, Topn), 
         caption = paste("Top CpGs from ", n_cpg, " for Outcome: ", Outcome_name, " of ", Gender," by p.value",
                         " (Sample Size = ", size, ") ", sep = "" , collapse = ""))
}


cpg_RegSimRaw <- function(outcome, CpGdata, Xs, Outcome_name, Topn, Gender){
  ## number of CpG to test, also the number of multiple test
  n_cpg = ncol(CpGdata)
  ## outcome lm
  outcome_lm = lapply(1:n_cpg, function(i){
  lm = lm(outcome ~ CpGdata[ ,i] + Race + Bcell + CD4T +
            CD8T + Gran + Mono + NK + nRBC, data = Xs)
  coef = summary(lm)$coefficients[2, ]
  return(coef)
})
   outcome_lm = data.frame(matrix(unlist(outcome_lm), ncol = 4, byrow = TRUE,
                          dimnames = list(
                     c(colnames(CpGdata)),
                        c("Estimate", "Std.Error", "t.statistic", "p.value"))))

   # adjusted p-value
    outcome_lm =  outcome_lm %>% 
                              mutate(FDR = p.adjust(p.value, "BH", n_cpg ),
                                               names = colnames(CpGdata)) %>% 
                                               mutate(Estimate = round(Estimate ,4),
                                                      Std.Error = round(Std.Error,4),
                                                      t.statistic = round(t.statistic,4)
                                                      )%>% 
                                               select(names, everything())
   # sort by p.value
    outcome_lm = outcome_lm[order(outcome_lm$p.value), ]
 
   ## sample size 
    size = length(outcome) - sum(is.na(outcome))

   ## raw_data
   head(outcome_lm, Topn)
}

```



```{r FunReg}
## equal length of outcomes and covariates
cpg_FunReg <- function(outcome, CpGdata, Xs, Outcome_name, Topn, Gender){
  ## number of CpG to test, also the number of multiple test
  n_cpg = ncol(CpGdata)
  ## outcome lm
  outcome_lm = lapply(1:n_cpg, function(i){
  lm = lm(outcome ~ CpGdata[ ,i] + maternal_age + Race + Bcell + CD4T +
            CD8T + Gran + Mono + NK + nRBC , data = Xs)
  coef = summary(lm)$coefficients[2, ]
  return(coef)
})
   outcome_lm = data.frame(matrix(unlist(outcome_lm), ncol = 4, byrow = TRUE,
                          dimnames = list(
                     c(colnames(CpGdata)),
                        c("Estimate", "Std.Error", "t.statistic", "p.value"))))

   # adjusted p-value
    outcome_lm =  outcome_lm %>% 
                              mutate(FDR = p.adjust(p.value, "BH", n_cpg ),
                                               names = colnames(CpGdata)) %>% 
                                               mutate(Estimate = round(Estimate ,4),
                                                      Std.Error = round(Std.Error,4),
                                                      t.statistic = round(t.statistic,4)
                                                      )%>% 
                                               select(names, everything())
   # sort by p.value
    outcome_lm = outcome_lm[order(outcome_lm$p.value), ]
 
   ## sample size 
    size = length(outcome) - sum(is.na(outcome))

   ## summary table 
   kable(head(outcome_lm, Topn), 
         caption = paste("Top CpGs from ", n_cpg, " for Outcome: ", Outcome_name, " of ", Gender," by p.value",
                         " (Sample Size = ", size, ") ", sep = "" , collapse = ""))
 
}

```

```{r simplemale, results='asis'}

## # the regression summary table for log10 outcomes 
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(pfas_malecpg[, x]), pfas_malecpg[, 21:123], pfas_malecpg[, out_cov], x, 10, "Male log10")
})
```
```{r rawmale}

lapply(Outcomes, function(x){
  cpg_RegSimRaw(log10(pfas_malecpg[, x]), pfas_malecpg[, 21:123], pfas_malecpg[, out_cov], x, 10, "Male log10")
})
```



```{r simplefemale, results='asis'}

## # the regression summary table for log10 outcomes 
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(pfas_femalecpg[, x]), pfas_femalecpg[, 21:58], pfas_femalecpg[, out_cov], x, 10, "Female log10")
})
```

```{r rawfemale}

lapply(Outcomes, function(x){
  cpg_RegSimRaw(log10(pfas_femalecpg[, x]), pfas_femalecpg[, 21:58], pfas_femalecpg[, out_cov], x, 10, "Female log10")
})
```




