---
title: "Plots_PFOA"
author: "Guannan Shen"
date: "December 5, 2018"
output:
  pdf_document:
    latex_engine: lualatex
    number_sections: yes
    toc: yes
    toc_depth: 5
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 5
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '5'
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
opts_chunk$set(engine = "R")
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
## setting wd in DELL
## opts_knit$set(root.dir = "~/Stats/CIDA_OMICs/CIDA_OMICS/7659Stats_Genetics/HW5/")
## setting working directory in asus 
opts_knit$set(root.dir = "C:/Users/hithr/Documents/Stats/gitlab/ECCHO_github/DataRaw/") 
## setting working directory in ubuntu

## opts_knit$set(root.dir = "~/Documents/gitlab/ECCHO_github/DataRaw/")
                                                 
## cache = F, if cache = T, will not revaluate code chunk everytime
## double or more space to insert a line break
```


```{r libs}
## set up workspace
library(data.table)
library(EnhancedVolcano)
library(knitr)
library(tidyverse)
library(magrittr)
library(stats)
library(gtable)
library(RColorBrewer)
library(grid) # low-level grid functions are required
options(stringsAsFactors = F)
options(dplyr.width = Inf)
getwd()
## not in function
'%nin%' <- Negate('%in%')

# ######## clean memory ######################
# rm(list = ls())
# gc()
# slotNames(x)
# getSlots(x)

```


```{r importdata}
# the result of pfoa concentration and all 450k cpgs
pfoa_coef <- fread("CpG_all_pfoa.txt", header = T)
head(pfoa_coef)
print("the coef of pfoa, means change in M values")
colnames(pfoa_coef)

## pid, pfoa concentration and cpg M values, and clinical gender information 
pid583 <- fread("pid583.csv")
pid583 <- as.vector(unlist(pid583))

pfoa_conc <- fread("pid583_pfoa.csv")
pfoa_conc_log <- pfoa_conc %>% dplyr::mutate(log2pfoa = log2(PFOA_ng_ml),
                                             lnpfoa = log(PFOA_ng_ml, base = exp(1)) )
write.csv(pfoa_conc_log,
          file = "C:/Users/hithr/Documents/Stats/gitlab/ECCHO_github/DataProcessed/pid583_pfoa_log.csv",
          row.names=FALSE)

m300 <- fread("HS_450K_CB_Mval_normbatch_StarlingSubset_10-01-18.csv")
pfas_clinical <- read_csv("pfas_methyl_di.csv")

## get pid for male and female 583 subjects
## infant_sex == 2 male infant_sex == 1 female 
pid_female <- pfas_clinical %>% filter(pid %in% pid583) %>% filter(infant_sex == 1) %>% select(pid)

pid_male <- pfas_clinical %>% filter(pid %in% pid583) %>% filter(infant_sex == 2) %>% select(pid)


### the 433360 cpgs list 
filtered_cpgs <- fread("MeanBeta_ExtremePFOA_M/MeanBeta_ExtremePFOA_F.txt", header = F)
dim(filtered_cpgs)
colnames(filtered_cpgs)

filtered_cpgs <- filtered_cpgs %>% dplyr::select(V1)
colnames(filtered_cpgs) <- "CpGs"
head(filtered_cpgs)
dim(filtered_cpgs)
write.csv(filtered_cpgs, 
          file = "C:/Users/hithr/Documents/Stats/gitlab/ECCHO_github/DataProcessed/filtered_cpgs.csv"
          , row.names=FALSE)

```

```{r scatter}
## top 3 cpg based on the association with pfoa concentration
paste("cg00803922, cg18587484 in males, and cg19425295 in females")
## check m values 
"cg00803922" %in% colnames(m300)
"cg18587484" %in% colnames(m300)
"cg19425295" %in% colnames(m300)

## top CpG for male and female
## male 103 and female 38
cpg_male <- read.delim("583_top_CpG_from_DMR_adjusted_M005.txt")

cpg_female <- read.delim("583_top_CpG_from_DMR_adjusted_F005.txt")
"cg00803922" %in% cpg_male$CpG
"cg18587484" %in% cpg_male$CpG
"cg19425295" %in% cpg_male$CpG

"cg00803922" %in% cpg_female$CpG
"cg18587484" %in% cpg_female$CpG
"cg19425295" %in% cpg_female$CpG


## m values for female top cpg cg19425295
f38  <- read_csv("HS_450K_CB_Mval_normbatch_StarlingSubset_FEMALE_10-29-18.csv")

## m values for top cpg in male cg00803922, cg18587484
m2cpg <- read_csv("HS_450K_CB_Mval_normbatch_StarlingSubset_MALE_12-6-18.csv")
head(m2cpg)
dim(m2cpg)

# get the index
which( colnames(f38) %in% "cg19425295")
# the index is 24
pfoa_cpg_female <- as.data.frame(f38[, c(1,24)]) %>% filter(pid %in%  as.vector(unlist(pid_female))  )
pfoa_M_Beta_female <- merge(pfoa_cpg_female, pfoa_conc, by = "pid") %>%
                    rename(M = cg19425295) %>%
                    mutate(Beta = 2^M/(1 + 2^M))
colnames(pfoa_M_Beta_female)
head(pfoa_M_Beta_female)
# plot separately
p1 <-  ggplot(data = pfoa_M_Beta_female, mapping = aes(x = PFOA_ng_ml, y = M)) + 
  ylab("M Values of cg19425295 (Female)") +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) )

p2 <-  ggplot(data = pfoa_M_Beta_female, mapping = aes(x = PFOA_ng_ml, y = Beta)) + 
  ylab("% Methylation of cg19425295 (Female)") +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) )
  
p1
p2
## convert plots to gtable objects

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- base::rbind(g1, g2, size="last") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)

###
# plot separately log e of x
p1 <-  ggplot(data = pfoa_M_Beta_female, mapping = aes(x = log(PFOA_ng_ml), y = M)) + 
  ylab("M Values of cg19425295 (Female)") +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) )

p2 <-  ggplot(data = pfoa_M_Beta_female, mapping = aes(x = log(PFOA_ng_ml), y = Beta)) + 
  ylab("% Methylation of cg19425295 (Female)") +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) )
  
p1
p2

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- base::rbind(g1, g2, size="last") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)


#################################
## scatter plots for male 
pfoa_cpg_male <- as.data.frame(m2cpg) %>% filter(pid %in%  as.vector(unlist(pid_male))  )
dim(pfoa_cpg_male)
head(pfoa_cpg_male)
pfoa_M_Beta_male <- merge(pfoa_cpg_male, pfoa_conc, by = "pid") %>% 
                    mutate(Beta1 = 2^cg00803922/(1 + 2^cg00803922),
                           Beta2 = 2^cg18587484/(1 + 2^cg18587484))
colnames(pfoa_M_Beta_male)
head(pfoa_M_Beta_male)

pfoa_M_Beta_male_noout <- pfoa_M_Beta_male %>% filter(PFOA_ng_ml <= 5)
########### cg00803922 ################
# plot separately
p1 <-  ggplot(data = pfoa_M_Beta_male, mapping = aes(x = PFOA_ng_ml, y = cg00803922)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("M Values of cg00803922 (Male)") +
  theme_bw()

p2 <-  ggplot(data = pfoa_M_Beta_male, mapping = aes(x = PFOA_ng_ml, y = Beta1)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("% Methylation of cg00803922 (Male)") +
  theme_bw()
p1
p2
## convert plots to gtable objects

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- base::rbind(g1, g2, size="last") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)

#############################  cg18587484 ############################
# plot separately
p1 <-  ggplot(data = pfoa_M_Beta_male, mapping = aes(x = PFOA_ng_ml, y = cg18587484)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("M Values of cg18587484 (Male)") +
  theme_bw()

p2 <-  ggplot(data = pfoa_M_Beta_male, mapping = aes(x = PFOA_ng_ml, y = Beta2)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("% Methylation of cg18587484 (Male)") +
  theme_bw()
p1
p2
## convert plots to gtable objects

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- base::rbind(g1, g2, size="last") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)


########### cg00803922 ################
# plot separately
p1 <-  ggplot(data = pfoa_M_Beta_male_noout, mapping = aes(x = PFOA_ng_ml, y = cg00803922)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("M Values of cg00803922 (Male)") +
  theme_bw()

p2 <-  ggplot(data = pfoa_M_Beta_male_noout, mapping = aes(x = PFOA_ng_ml, y = Beta1)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("% Methylation of cg00803922 (Male)") +
  theme_bw()
p1
p2
## convert plots to gtable objects

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- base::rbind(g1, g2, size="last") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)

#################### no outliers #################333
#############################  cg18587484 ############################
# plot separately
p1 <-  ggplot(data = pfoa_M_Beta_male_noout, mapping = aes(x = PFOA_ng_ml, y = cg18587484)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("M Values of cg18587484 (Male)") +
  theme_bw()

p2 <-  ggplot(data = pfoa_M_Beta_male_noout, mapping = aes(x = PFOA_ng_ml, y = Beta2)) + 
  geom_point() +
  xlab("PFOA Concentration ng/ml") +
  ylab("% Methylation of cg18587484 (Male)") +
  theme_bw()
p1
p2
## convert plots to gtable objects

g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- base::rbind(g1, g2, size="last") # stack the two plots
g$widths <- unit.pmax(g1$widths, g2$widths) # use the largest widths
# center the legend vertically
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)



```


```{r volcano, fig.width= 8, fig.height= 6}

## the pfoa concentrations were categorized 
# the mean of beta values in each quartile
## the difference in beta value % methylation between the first and the fourth quartile 
## of the 583 pfoa concentrations 
## then straitified by gender 
######## female ###########
beta_diff_f <- fread("MeanBeta_ExtremePFOA_M/MeanBeta_ExtremePFOA_F.txt", header = F)
head(beta_diff_f)
##
dim(beta_diff_f)


# using the volcano plot to demonstrate the significance and the scope of the association
## the 3 cpgs
c("cg18587484","cg00803922", "Male", "cg19425295", "Female")
colnames(pfoa_coef)
##
pfoa_vol <- pfoa_coef %>% filter(CpG %in% beta_diff_f$V1) %>% dplyr::rename( rawpF = `P value F` ,
                                         rawpM = `P value M`) %>% 
                   dplyr::select(Chr, CpG, coefF, rawpF, qf, coefM, rawpM, qm)  %>% 
                       column_to_rownames("CpG")
dim(pfoa_vol)   
## top cpg
paste("Female")
head(pfoa_vol[order(pfoa_vol$rawpF), ], 8)
paste("Male")
head(pfoa_vol[order(pfoa_vol$rawpM), ], 8)
head(pfoa_coef[order(pfoa_coef$`P value M` ), ] , 8)


#  EnhancedVolcano plot
## Modify cut-offs for coefF and P value; add title; adjust point and label size
## Female
    EnhancedVolcano(pfoa_vol,
        lab = rownames(pfoa_vol),
        x = "coefF",
        y = "rawpF",
        xlab = bquote("Change in M Value per 1 ng/ml increase of PFOA (Female)"),
        title = "Association: M Value and PFOA Concentration in Female",
                ## select labels to show
        selectLab = c(
          ## based on the top q value
          "cg19425295",
          # # not q sig
          # "cg19729649","ch.7.54842076F",
          ## two cutoffs
          "cg14554788",
          "cg24636332",
          "cg17588704",
          "cg20040891",
          "cg10875794",
          "cg03858121"),
        ### two cutoffs
        pCutoff = 10e-4,

        FCcutoff = 0.15,
        xlim = c(-0.45, 0.45),
        ylim = c(0, -log10(10e-9)),
        # adjust the legend
        legend=c("NS","Slope","Raw p-value",
            "Raw p-value & Slope"),

        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,

        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,


        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        DrawConnectors = TRUE,
        # 
        widthConnectors = 0.2,
        # 
        colConnectors = "grey30"
        )
    
####### default labels


####################### Male ##############################
####### default labels
EnhancedVolcano(pfoa_vol,

        lab = rownames(pfoa_vol),

        x = "coefM",

        y = "rawpM",

        pCutoff = 10e-4,

        FCcutoff = 0.15,
        ## select labels to show
        selectLab = c(############ qm significant
          "cg18587484","cg00803922", 
          # "cg02819404", "cg08617337", "cg07818713",
          # # not q sig
          # "cg24446932", "cg13699963", "cg19055098",
          ############ based on two cut-offs
                      "cg23208443","cg17480035"),
        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,
        
        xlab = bquote("Change in M Value per 1 ng/ml increase of PFOA (Male)"),

        title = "Association: M Value and PFOA Concentration in Male",
        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,
        xlim = c(-0.4, 0.4),
        ylim = c(0, -log10(10e-10)),
        # adjust the legend
        legend=c("NS","Slope","Raw p-value",
            "Raw p-value & Slope"),

        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        DrawConnectors = TRUE,
        # 
        widthConnectors = 0.2,
        # 
        colConnectors = "grey30"
        )
    
EnhancedVolcano(pfoa_vol,

        lab = rownames(pfoa_vol),

        x = "coefM",

        y = "rawpM",

        pCutoff = 10e-4,

        FCcutoff = 0.2,
        ## select labels to show
        selectLab = c(############ qm significant
          "cg18587484","cg00803922","cg21209948" , "cg12472218",  "cg09331106",
          ############ based on two cut-offs
                      "cg23208443","cg17480035"),
        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,
        
        xlab = bquote("Change in M Value per 1 ng/ml increase of PFOA (Male)"),

        title = "Association: M Value and PFOA Concentration in Male",
        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,
        xlim = c(-0.4, 0.4),
        ylim = c(0, -log10(10e-10)),
        # adjust the legend
        legend=c("NS","Slope","Raw p-value",
            "Raw p-value & Slope"),

        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        DrawConnectors = TRUE,
        # 
        widthConnectors = 0.2,
        # 
        colConnectors = "grey30"
        )


```

```{r volcaBeta}
## the p value data
pfoa_vol_a <- rownames_to_column(pfoa_vol, "CpG")
head(pfoa_vol_a)

## the pfoa concentrations were categorized 
# the mean of beta values in each quartile
## the difference in beta value % methylation between the first and the fourth quartile 
## of the 583 pfoa concentrations 
## then straitified by gender 
######## female ###########
beta_diff_f <- fread("MeanBeta_ExtremePFOA_M/MeanBeta_ExtremePFOA_F.txt", header = F)
head(beta_diff_f)
##
dim(beta_diff_f)

colnames(beta_diff_f) <- c("CpG", "mean_25pct_female", 
                           "mean_75pct_female", "diff_75minus25_female")

beta_pfoadiff_f <- merge(beta_diff_f, pfoa_vol_a, by = "CpG") %>%  mutate(beta = diff_75minus25_female*100)
rownames(beta_pfoadiff_f) <- beta_pfoadiff_f$CpG

dim(beta_pfoadiff_f)

## volcano plot of beta values 
EnhancedVolcano(beta_pfoadiff_f,

        lab = rownames(beta_pfoadiff_f),

        x = "beta",

        y = "rawpF",

        pCutoff = 10e-4,

        FCcutoff = 4,
        ## select labels to show
        # selectLab = c("cg18587484","cg00803922", " cg19425295"),
        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,
        
        xlab = bquote("Mean Diff. in % Methylation between 1st and 4th quartiles of PFOA"),

        title = "Mean Difference in % Methylation (Female)",
        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,
        xlim = c(-11, 11),
        ylim = c(0, -log10(10e-10)),
        # adjust the legend
        legend=c("NS","Effect Size","Raw p-value",
            "Raw p-value & Effect Size"),

        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        ## drawConnectors = FALSE,
        DrawConnectors = TRUE,
        # 
        widthConnectors = 0.2,
        # 
        colConnectors = "grey30"
        )


EnhancedVolcano(beta_pfoadiff_f,

        lab = rownames(beta_pfoadiff_f),

        x = "beta",

        y = "rawpF",

        pCutoff = 10e-4,

        FCcutoff = 4,
        ## select labels to show
        selectLab = c("cg19425295","cg05313263"),
        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,
        
        xlab = bquote("Mean Diff. in % Methylation between 1st and 4th quartiles of PFOA"),

        title = "Mean Difference in % Methylation (Female)",
        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,
        xlim = c(-11, 11),
        ylim = c(0, -log10(10e-10)),
        # adjust the legend
        legend=c("NS","Effect Size","Raw p-value",
            "Raw p-value & Effect Size"),

        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        ## drawConnectors = FALSE,
        DrawConnectors = TRUE,
        # 
        widthConnectors = 0.2,
        # 
        colConnectors = "grey30"
        )

####### male ################
beta_diff_m <- fread("MeanBeta_ExtremePFOA_M/MeanBeta_ExtremePFOA_M.txt", header = F)
head(beta_diff_m)
colnames(beta_diff_m) <- c("CpG", "mean_25pct_male", 
                           "mean_75pct_male", "diff_75minus25_male")

beta_pfoadiff_m <- merge(beta_diff_m, pfoa_vol_a, by = "CpG") %>% mutate(beta = diff_75minus25_male*100)
rownames(beta_pfoadiff_m) <- beta_pfoadiff_m$CpG

##
dim(beta_diff_f)
dim(beta_diff_m)
head(beta_diff_f)

dim(beta_pfoadiff_m)

head(beta_pfoadiff_m)

## top cpgs male
head(beta_pfoadiff_m[ order(beta_pfoadiff_m$rawpM), ], 8)
head(beta_pfoadiff_m)
## volcano plot of beta values 
EnhancedVolcano(beta_pfoadiff_m,

        lab = rownames(beta_pfoadiff_m),

        x = "beta",

        y = "rawpM",

        pCutoff = 10e-4,

        FCcutoff = 4,
        ## select labels to show
        # selectLab = c("cg18587484","cg00803922", "cg19425295"),
        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,
        
        xlab = bquote("Mean Diff. in % Methylation between 1st and 4th quartiles of PFOA"),

        title = "Mean Difference in % Methylation (Male)",
        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,
        xlim = c(-12, 12),
        ylim = c(0, -log10(10e-10)),
        # adjust the legend
        legend=c("NS","Effect Size","Raw p-value",
            "Raw p-value & Effect Size"),

        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        ## drawConnectors = FALSE,
        # 
        widthConnectors = 0.2,
        DrawConnectors = TRUE,
        # 
        colConnectors = "grey30"
        )


EnhancedVolcano(beta_pfoadiff_m,

        lab = rownames(beta_pfoadiff_m),

        x = "beta",

        y = "rawpM",

        pCutoff = 10e-4,

        FCcutoff = 4,
        ## select labels to show
        selectLab = c("cg18587484","cg00803922",
                      "cg17480035", "cg02819404"),
        ## point and label size 
        transcriptPointSize = 2.0,

        transcriptLabSize = 3.5,
        
        xlab = bquote("Mean Diff. in % Methylation between 1st and 4th quartiles of PFOA"),

        title = "Mean Difference in % Methylation (Male)",
        #Modify border and remove gridlines
        gridlines.major = FALSE,

        gridlines.minor = FALSE,
        
        border = "full",

        borderWidth = 1.0,

        borderColour = "black",
        # the transparence of the dots
        colAlpha = 0.7,
        xlim = c(-12, 12),
        ylim = c(0, -log10(10e-10)),
        # adjust the legend
        legend=c("NS","Effect Size","Raw p-value",
            "Raw p-value & Effect Size"),

        legendPosition = "bottom",

        legendLabSize = 12,

        legendIconSize = 3.5,
        # connectors
        ## drawConnectors = FALSE,
        # 
        widthConnectors = 0.2,
        DrawConnectors = TRUE,
        # 
        colConnectors = "grey30"
        )

## 
c( "cg18587484","cg00803922", "cg02819404", "cg08617337", "cg07818713") %in% beta_diff_m$CpG

```
## Questions
```{r questions}
paste("1. M values of more selected CpGs.", 
      "2. Why the number of CpGs diff between the association with PFOA data and the Diff between quartiles data, 484261 vs 433360",
      "3. Why the patterns of %Methylation volcano plot are wrong",
      sep = "\n")

## More M-values
############# Female
c(
          ## based on the top q value
          "cg19425295",
          # not q sig
          "cg19729649","ch.7.54842076F",
          ## two cutoffs
          "cg14554788",
          "cg24636332",
          "cg17588704",
          "cg20040891",
          ## beta values
          "cg05313263")
################# Male
c(############ qm significant
          "cg18587484","cg00803922", "cg02819404", "cg08617337", "cg07818713",
          # not q sig
          "cg24446932", "cg13699963", "cg19055098", "cg21209948" , "cg12472218",  "cg09331106", 
          ############ based on two cut-offs
                      "cg23208443","cg17480035")
"ch.7.54842076F" %in% pfoa_coef$CpG

## more cpg female
c("cg10875794", "cg03858121")
```

```{r morescatter}
##  using previous loaded pid_male and pid_female
pid_female <- as.vector(unlist(pid_female)) 
pid_male <- as.vector(unlist(pid_male)) 
head(pfoa_conc)
## scatter plot function

scatter_gender_mb <- function(cpgname, gender, mvalue_df, pfoa_conc){
    ## select corresponding mvalue and pid
   mvalue_df = data.frame(mvalue_df)
  df = mvalue_df[, colnames(mvalue_df) %in% c("pid", cpgname)]
  if(gender == "Male")
    {
    ##  using previous loaded pid_male
    ########## get dataset ready for scatter plot ################
    df_male = df %>% filter(pid %in% pid_male)
    df_male = merge(df_male, pfoa_conc, by = "pid") 
    df_male$Beta = 2^df_male[,2]/(1 + 2^df_male[,2])
    
    ################ scatter plot ###########################
    p1 =  ggplot(data = df_male , mapping = aes(x = df_male[,3], y = df_male$cpgname )) + 
  ylab( paste("M Values of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85, 
             y = quantile(df_male$cpgname, 0.95), 
             label = paste(cpgname, gender, sep = "\n"))
    
    p3 = ggplot(data = df_male , mapping = aes(x = df_male[,3], y = df_male[,4] )) + 
  ylab( paste("% Methylation of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85, 
             y = quantile(df_male[,4], 0.95), 
             label =  paste(cpgname, gender, sep = "\n") )
    
    return(list(p1,p3))
  }
  else if(gender == "Female")
    {
     ########## get dataset ready for scatter plot ################
        df_female = df %>% filter(pid %in% pid_female)
    df_female = merge(df_female, pfoa_conc, by = "pid")
     df_female$Beta = 2^df_female[,2]/(1 + 2^df_female[,2])
    
    ################ scatter plot ###########################
p2 =  ggplot(data = df_female , mapping = aes(x = df_female[,3], y = df_female[,2] ) ) + 
  ylab( paste("M Values of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_female[,3])*0.85, 
             y = quantile(df_female$cpgname, 0.95), 
             label =  paste(cpgname, gender, sep = "\n"))
     
p4 = ggplot(data = df_female , mapping = aes(x = df_female[,3], y = df_female[,4])) + 
  ylab( paste("% Methylation of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_female[,3])*0.85, 
             y = quantile(df_female[,4], 0.95), 
             label = paste(cpgname, gender, sep = "\n"))
    
    return(list(p2,p4))
  }
  else 
    {
    stop("Gender should be Male or Female")
  }
}

## 
m.cpgs.more <- read.csv("cpgsForGuannan01-22-19.csv")
head(m.cpgs.more)
## how to select m.cpgs.more[, colnames(m.cpgs.more) %in% c("pid", "cg19425295")]
cpgnames.scatter <- data.frame(cpgname = c(  "cg19425295", "cg19729649","ch.7.54842076F", "cg05313263",
                                             "cg10875794", "cg03858121",
                                        ## Male
                                        "cg18587484","cg00803922", "cg21209948" , "cg12472218",  
                                        "cg09331106","cg17480035"), 
                          gender = c(rep("Female", 6), 
                                     rep("Male", 6)) )


## more cpg
c("cg10875794", "cg03858121") ## Female 

# #  
# 
# scatter_gender_mb("cg19425295", "Female", m.cpgs.more, pfoa_conc)
# 
# # scatter_gender <- function(cpgname, gender, mvalue_df, pfoa_conc){
#     ## select corresponding mvalue and pid
# 
# #     %>% 
# #       dplyr::mutate(Beta = 2^df_male$cpgname/(1 + 2^df_male$cpgname)) 
# #     return(df_male) 
# #     }
# # head(scatter_gender("cg19425295", "Male", m.cpgs.more, pfoa_conc))
# 
## fianl run
# for( i in nrow(cpgnames.scatter)){
#   ## cpgname, gender, mvalue_df, pfoa_conc
#   print( scatter_gender_mb(cpgnames.scatter[i,1], cpgnames.scatter[i,2],
#                           m.cpgs.more, pfoa_conc) )
# }
########################## Male #####################################
######## M value ############
for( i in 7:12){
   mvalue_df = data.frame(m.cpgs.more)
   cpgname = cpgnames.scatter[i ,1]
   gender = cpgnames.scatter[i ,2]
  df = mvalue_df[, colnames(mvalue_df) %in% c("pid", cpgname)]
df_male = df %>% filter(pid %in% pid_male)
    df_male = merge(df_male, pfoa_conc, by = "pid")
    df_male$Beta = 2^df_male[,2]/(1 + 2^df_male[,2])

    ################ scatter plot ###########################
    p1 =  ggplot(data = df_male , mapping = aes(x = df_male[,3], y = df_male[,2] )) +
  ylab( paste("M Values of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85,
             y = quantile(df_male[,2], 0.95),
             label = paste(cpgname, gender, "M values",sep = "\n"))
print(p1)
}
################ Beta #####################
for( i in 7:12){
   mvalue_df = data.frame(m.cpgs.more)
   cpgname = cpgnames.scatter[i ,1]
   gender = cpgnames.scatter[i ,2]
  df = mvalue_df[, colnames(mvalue_df) %in% c("pid", cpgname)]
df_male = df %>% filter(pid %in% pid_male)
    df_male = merge(df_male, pfoa_conc, by = "pid")
    df_male$Beta = 2^df_male[,2]/(1 + 2^df_male[,2])

    ################ scatter plot ###########################
    p1 =  ggplot(data = df_male , mapping = aes(x = df_male[,3], y = Beta )) +
  ylab( paste("% Methylation of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85,
             y = quantile(df_male[,4], 0.95),
             label = paste(cpgname, gender, "% Methylation",sep = "\n"))
print(p1)
    }


########################## Female #####################################
######## M value ############
for( i in 1:6){
   mvalue_df = data.frame(m.cpgs.more)
   cpgname = cpgnames.scatter[i ,1]
   gender = cpgnames.scatter[i ,2]
  df = mvalue_df[, colnames(mvalue_df) %in% c("pid", cpgname)]
  ############ pid_female ###############
df_male = df %>% filter(pid %in% pid_female)
    df_male = merge(df_male, pfoa_conc, by = "pid")
    df_male$Beta = 2^df_male[,2]/(1 + 2^df_male[,2])

    ################ scatter plot ###########################
    p1 =  ggplot(data = df_male , mapping = aes(x = df_male[,3], y = df_male[,2] )) +
  ylab( paste("M Values of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85,
             y = quantile(df_male[,2], 0.95),
             label = paste(cpgname, gender, "M values",sep = "\n"))
print(p1)
}
################ Beta #####################
for( i in 1:6){
   mvalue_df = data.frame(m.cpgs.more)
   cpgname = cpgnames.scatter[i ,1]
   gender = cpgnames.scatter[i ,2]
  df = mvalue_df[, colnames(mvalue_df) %in% c("pid", cpgname)]
    ############ pid_female ###############
df_male = df %>% filter(pid %in% pid_female)
    df_male = merge(df_male, pfoa_conc, by = "pid")
    df_male$Beta = 2^df_male[,2]/(1 + 2^df_male[,2])

    ################ scatter plot ###########################
    p1 =  ggplot(data = df_male , mapping = aes(x = df_male[,3], y = Beta )) +
  ylab( paste("% Methylation of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85,
             y = quantile(df_male[,4], 0.95),
             label = paste(cpgname, gender, "% Methylation",sep = "\n"))
print(p1)
    }


```
```{r testscatter}


mvalue_df = data.frame(m.cpgs.more)
   cpgname = cpgnames.scatter[5 ,1]
   cpgname
   gender = cpgnames.scatter[5 ,2]
   gender
  df = mvalue_df[, colnames(mvalue_df) %in% c("pid", cpgname)]
df_male = df %>% filter(pid %in% pid_male)
    df_male = merge(df_male, pfoa_conc, by = "pid") 
    df_male$Beta = 2^df_male[,2]/(1 + 2^df_male[,2])
    df_male
    
    ################ scatter plot ###########################
    p1 =  ggplot(data = df_male , mapping = aes(x = df_male[,3], y = df_male[,2] )) + 
  ylab( paste("M Values of ",cpgname," ", "(", gender, ")" , sep = "" ) ) +
  geom_point(colour = "gray15", size = 2, shape = 20) +
  geom_smooth(method = "loess", se = FALSE, colour = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, colour = "tomato") +
  xlab("PFOA Concentration ng/ml") +
  theme_bw() +
  theme(
    plot.title = element_text(color="black", size=14, face="bold.italic"),
    axis.title.x = element_text(color="black", size=12, face="bold"),
    axis.title.y = element_text(color="black", size=12, face="bold"),
    axis.text.x = element_text(face="bold", color="black", size=10, angle=0),
    axis.text.y = element_text(face="bold", color="black", size=10, angle=0) ) +
    annotate("text", x = max(df_male[,3])*0.85 , 
             y = quantile(df_male[,2], 0.95), 
             label = paste(cpgname, gender, sep = "\n"))
 print(list(p1))
```


```{r logpfoa}
# the result of pfoa concentration and all 450k cpgs
pfoa_log_raw <- fread("log_CpG_all_logpfoa.txt", header = T)
head(pfoa_log)

# filter the data from 484261 cpgs to 433360 cpgs
head(beta_diff_f)
pfoa_log <- merge(pfoa_log_raw, beta_diff_f, by = "CpG") %>% dplyr::select(- mean_25pct_female, 
                                                                           - mean_75pct_female,
                                                                           - diff_75minus25_female)
dim(pfoa_log)
colnames(pfoa_log)

## rank the data by qf and qm
######### female #########
pfoa_log_f <- pfoa_log[order(pfoa_log$qf), ]
pfoa_log_f[pfoa_log_f$qf <= 0.05 ,]
head(pfoa_log_f)
######### male ############
pfoa_log_m <- pfoa_log[order(pfoa_log$qm), ]
pfoa_log_m[pfoa_log_m$qm <= 0.05 ,]
head(pfoa_log_m)

```

