---
title: "fdr005 dmps with obesity outcomes"
author: "Guannan Shen"
date: "August 4, 2019"
output: 
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 5
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '5'
  pdf_document:
    latex_engine: lualatex
    number_sections: yes
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
opts_chunk$set(engine = "R")
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
## setting wd in DELL
## opts_knit$set(root.dir = "~/Stats/CIDA_OMICs/CIDA_OMICS/7659Stats_Genetics/HW5/")
## setting working directory in asus 
## opts_knit$set(root.dir = "C:/Users/hithr/Documents/Stats/gitlab/Cario_RNASeq_Microbiom_Inte/DataRaw/") 
## setting working directory in ubuntu
opts_knit$set(root.dir = "~/Documents/gitlab/ECCHO_github/DataProcessed/3chems_results_data/")
                                                 
## cache = F, if cache = T, will not revaluate code chunk everytime
## double or more space to insert a line break
```

```{r libs, echo=FALSE }
## set up workspace
rm(list = ls())
library(data.table)
library(knitr)
library(tidyverse)
library(magrittr)
library(stats)
library(readxl)
library(mutoss)
options(stringsAsFactors = F)
options(dplyr.width = Inf)
getwd()
## not in function
'%nin%' <- Negate('%in%')

# ######## clean memory ######################
# rm(list = ls())
# gc()
# ls()
# slotNames(x)
# getSlots(x)

```

```{r importcpg_mval}
# import cpgs which are fdr 005 from DMP analysis
dir <- "~/Documents/gitlab/ECCHO_github/DataProcessed/3chems_results_data/fdr005_dmps/"
Mtop_f_pfhxs <- read.csv(paste0(dir, "Mval_top_f_pfhxs_.csv"))
Mtop_f_pfos <- read.csv(paste0(dir, "Mval_top_f_pfos_.csv"))
Mtop_f_pfoa <- read.csv(paste0(dir, "Mval_top_f_pfoa_.csv"))

Mtop_m_pfhxs <- read.csv(paste0(dir, "Mval_top_m_pfhxs_.csv"))
Mtop_m_pfos <- read.csv(paste0(dir, "Mval_top_m_pfos_.csv"))
Mtop_m_pfoa <- read.csv(paste0(dir, "Mval_top_m_pfoa_.csv"))

######
dir <- "/home/guanshim/Documents/gitlab/ECCHO_github/DataRaw/more_pfas/combp_DMR/Mval/"
Mtop_f_pfdea <- read.csv(paste0(dir, "_top_f_pfdea_.csv"))
Mtop_f_pfna <- read.csv(paste0(dir, "_top_f_pfna_.csv"))

Mtop_m_pfdea <- read.csv(paste0(dir, "_top_m_pfdea_.csv"))
Mtop_m_pfna <- read.csv(paste0(dir, "_top_m_pfna_.csv"))
Mtop_m_pfdea %>% dim()
########## get chem conc
# all clinical data, chemical conc, obesity outcomes
clinchem_f <- read.csv("/home/guanshim/Documents/gitlab/ECCHO_github/DataProcessed/clin_chem_f.csv")
clinchem_m <- read.csv("/home/guanshim/Documents/gitlab/ECCHO_github/DataProcessed/clin_chem_m.csv")
sum(Mtop_f_pfhxs$pid != clinchem_f$pid) == 0

sum(Mtop_f_pfdea$pid != clinchem_f$pid) == 0

## read in data 
pfas_cell_583 <- read.csv("~/Documents/gitlab/ECCHO_github/DataProcessed/for_obesity/11_05_pfas_cell_583.csv")
Outcomes <- colnames(pfas_cell_583)[5:13]
Outcomes

```


## Correlation

```{r r corre}
## equal length of outcomes and covariates
cpg_FunRegSim <- function(outcome, CpGdataPid, Xs, Outcome_name, Topn, chemname){
  ## get the gender 
  gender1 = unlist(strsplit( deparse(substitute(Xs)), "_", fixed = T))[2]
  gender2 = unlist(strsplit( deparse(substitute(CpGdataPid)), "_", fixed = T))[2]
  if(gender1 != gender2)
    stop("Should use data of the same gender!")
  if(   sum(CpGdataPid$pid != Xs$pid) != 0  )
    stop("Wrong pid order!")
  Gender = ifelse(gender1 == "m", "male", "female")
  # the first column of CpG data is pid 
  CpGdata = as.matrix(as.matrix(CpGdataPid[,-1] ) )
  ## number of CpG to test, also the number of multiple test
  n_cpg = ncol(CpGdata) 
  ## outcome lm
  outcome_lm = lapply(1:n_cpg, function(i){
  lmregress = lm(CpGdata[ ,i] ~ Bcell + CD4T + CD8T + Gran + Mono + NK + nRBC, data = Xs)
  xcpg = resid(lmregress)
  lm = lm(outcome ~ xcpg + Race, data = Xs)
  coef = summary(lm)$coefficients[2, ]
  return(coef)
})
   outcome_lm = data.frame(matrix(unlist(outcome_lm), ncol = 4, byrow = TRUE,
                          dimnames = list(
              # the first column of CpG data is pid
                     c(colnames(CpGdata)),
                        c("Estimate", "Std.Error", "t.statistic", "p.value"))))

   # adjusted p-value
    outcome_lm =  outcome_lm %>% 
                              mutate(FDR = if(n_cpg >= 17)
                                       {p.adjust(p.value, "BH", n_cpg )}
                                     else { BL(p.value, 0.05, silent = TRUE )$adjPValues },
                                     names = colnames(CpGdata)) %>% 
                                               mutate(Estimate = round(Estimate ,4),
                                                      Std.Error = round(Std.Error,4),
                                                      t.statistic = round(t.statistic,4)
                                                      )%>% 
                                               select(names, everything()) %>% arrange(p.value)
   # sort by p.value
    outcome_lm = data.frame(outcome_lm)
 
   ## sample size 
    size = length(outcome) - sum(is.na(outcome))
   ## save results per outcome 
    dir = "/home/guanshim/Documents/gitlab/ECCHO_github/DataRaw/more_pfas/combp_DMR/obesity_corre/"
    write.csv(outcome_lm, paste( dir, Sys.Date(), Gender, Outcome_name, chemname, ".csv", sep="_"), row.names = F)
   ## summary table 
   # kable(head(outcome_lm, Topn), 
   #       caption = paste("Top CpGs from ", n_cpg," CpGs" ," for Outcome: ", Outcome_name, " of ", Gender, " ", chemname, " (Sample Size = ", size, ") ", sep = "" , collapse = ""))
}

```


```{r runcorr}
## # the regression summary table for log10 outcomes 
# function(outcome, CpGdata, Xs, Outcome_name, Topn, chemname)
n <- 10 
###############
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_f[, x]), Mtop_f_pfdea, clinchem_f, x, n, "pfdea")
})
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_f[, x]), Mtop_f_pfna, clinchem_f, x, n, "pfna")
})

lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_m[, x]), Mtop_m_pfdea, clinchem_m, x, n, "pfdea")
})
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_m[, x]), Mtop_m_pfna, clinchem_m, x, n, "pfna")
})

Mtop_m_pfdea %>% dim()


###########3
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_f[, x]), Mtop_f_pfhxs, clinchem_f, x, n, "pfhxs")
})
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_f[, x]), Mtop_f_pfos, clinchem_f, x, n, "pfos")
})
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_f[, x]), Mtop_f_pfoa, clinchem_f, x, n, "pfoa")
})

####### male 
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_m[, x]), Mtop_m_pfhxs, clinchem_m, x, n, "pfhxs")
})
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_m[, x]), Mtop_m_pfos, clinchem_m, x, n, "pfos")
})
lapply(Outcomes, function(x){
  cpg_FunRegSim(log10(clinchem_m[, x]), Mtop_m_pfoa, clinchem_m, x, n, "pfoa")
})
```


## validation

```{r scatter}
# ## mval vs chemical concentration, should be mval vs log10 outcome, obesity as the outcome
# ## of the regression
# doscatter <- function(mval, chem){
#   if(sum(mval$pid != chem$pid) != 0)
#   stop("Wrong pid order!")
#   gender1 = unlist( strsplit(deparse(substitute(mval)), "_", fixed = T))  [2]
#   gender2 = unlist( strsplit(deparse(substitute(chem)), "_", fixed = T))  [2]
#   if(gender1 != gender2)
#     {stop("Use same gender for both datasets")}
#   else{
#     gender = ifelse(gender1 == "f", "Female", "Male") 
#   }
#   chemname = unlist( strsplit(deparse(substitute(mval)), "_", fixed = T))  [3]
#   xname = paste("ln", chemname, sep = "")
#   x = chem[, colnames(chem) == xname]
#   ncpg = ncol(mval) - 1
#   for (i in 1:ncpg) {
#     j = i+1
#     cpg = colnames(mval)[j]
#     ggplot( mval,aes(x, mval[, j]) ) +
#           geom_point() +
#             xlab(paste(xname,gender, sep = "_" ) ) +
#             ylab(paste("M Values of ", sep = "", cpg) ) +
#            geom_smooth(method = "lm", se = F) +
#            theme_minimal()
#     ggsave( paste("~/Documents/gitlab/ECCHO_github/DataProcessed/3chems_results_data/fdr005_dmps/plots/", xname, cpg, gender,sep = "_", ".png" ) )
#   }
# }
# 
# doscatter(Mtop_f_pfhxs, clinchem_f)
# doscatter(Mtop_f_pfos, clinchem_f)
# doscatter(Mtop_f_pfoa, clinchem_f)
# 
# doscatter(Mtop_m_pfhxs, clinchem_m)
# doscatter(Mtop_m_pfos, clinchem_m)
# doscatter(Mtop_m_pfoa, clinchem_m)
```